# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QApplication, QComboBox, QDoubleSpinBox, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QMainWindow,
    QPushButton, QSizePolicy, QSpinBox, QStatusBar,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1028, 790)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(0, 0, 1021, 771))
        self.settings = QWidget()
        self.settings.setObjectName(u"settings")
        self.label_5 = QLabel(self.settings)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(320, 140, 221, 16))
        self.label = QLabel(self.settings)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 221, 16))
        self.pushButton_loadSettings = QPushButton(self.settings)
        self.pushButton_loadSettings.setObjectName(u"pushButton_loadSettings")
        self.pushButton_loadSettings.setGeometry(QRect(0, 270, 1001, 61))
        self.label_2 = QLabel(self.settings)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 70, 221, 16))
        self.label_4 = QLabel(self.settings)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(320, 70, 221, 16))
        self.spinBox_cell_para = QSpinBox(self.settings)
        self.spinBox_cell_para.setObjectName(u"spinBox_cell_para")
        self.spinBox_cell_para.setGeometry(QRect(320, 100, 231, 22))
        self.spinBox_cell_para.setMinimum(1)
        self.spinBox_cell_para.setMaximum(10)
        self.spinBox_cell_para.setValue(5)
        self.label_3 = QLabel(self.settings)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(320, 10, 221, 16))
        self.doubleSpinBox_efficiency = QDoubleSpinBox(self.settings)
        self.doubleSpinBox_efficiency.setObjectName(u"doubleSpinBox_efficiency")
        self.doubleSpinBox_efficiency.setGeometry(QRect(10, 40, 241, 22))
        self.doubleSpinBox_efficiency.setMaximum(1.000000000000000)
        self.doubleSpinBox_efficiency.setSingleStep(0.010000000000000)
        self.doubleSpinBox_efficiency.setValue(0.850000000000000)
        self.doubleSpinBox_torque_constant = QDoubleSpinBox(self.settings)
        self.doubleSpinBox_torque_constant.setObjectName(u"doubleSpinBox_torque_constant")
        self.doubleSpinBox_torque_constant.setGeometry(QRect(10, 100, 241, 22))
        self.doubleSpinBox_torque_constant.setMinimum(0.010000000000000)
        self.doubleSpinBox_torque_constant.setMaximum(10.000000000000000)
        self.doubleSpinBox_torque_constant.setSingleStep(0.100000000000000)
        self.doubleSpinBox_torque_constant.setValue(1.500000000000000)
        self.doubleSpinBox_cell_capacity = QDoubleSpinBox(self.settings)
        self.doubleSpinBox_cell_capacity.setObjectName(u"doubleSpinBox_cell_capacity")
        self.doubleSpinBox_cell_capacity.setGeometry(QRect(320, 40, 241, 22))
        self.doubleSpinBox_cell_capacity.setMinimum(0.100000000000000)
        self.doubleSpinBox_cell_capacity.setMaximum(10.000000000000000)
        self.doubleSpinBox_cell_capacity.setSingleStep(0.100000000000000)
        self.doubleSpinBox_cell_capacity.setValue(4.000000000000000)
        self.doubleSpinBox_initial_soc = QDoubleSpinBox(self.settings)
        self.doubleSpinBox_initial_soc.setObjectName(u"doubleSpinBox_initial_soc")
        self.doubleSpinBox_initial_soc.setGeometry(QRect(320, 170, 241, 22))
        self.doubleSpinBox_initial_soc.setMinimum(0.010000000000000)
        self.doubleSpinBox_initial_soc.setMaximum(1.000000000000000)
        self.doubleSpinBox_initial_soc.setSingleStep(0.050000000000000)
        self.doubleSpinBox_initial_soc.setValue(1.000000000000000)
        self.label_6 = QLabel(self.settings)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 330, 281, 20))
        self.pushButton_loadFile = QPushButton(self.settings)
        self.pushButton_loadFile.setObjectName(u"pushButton_loadFile")
        self.pushButton_loadFile.setGeometry(QRect(10, 390, 481, 41))
        self.lineEdit_loadedFile = QLineEdit(self.settings)
        self.lineEdit_loadedFile.setObjectName(u"lineEdit_loadedFile")
        self.lineEdit_loadedFile.setGeometry(QRect(10, 360, 981, 20))
        self.lineEdit_loadedFile.setReadOnly(True)
        self.pushButton_startSimulation = QPushButton(self.settings)
        self.pushButton_startSimulation.setObjectName(u"pushButton_startSimulation")
        self.pushButton_startSimulation.setGeometry(QRect(10, 510, 371, 181))
        self.doubleSpinBox_bikeweight = QDoubleSpinBox(self.settings)
        self.doubleSpinBox_bikeweight.setObjectName(u"doubleSpinBox_bikeweight")
        self.doubleSpinBox_bikeweight.setGeometry(QRect(640, 50, 241, 22))
        self.doubleSpinBox_bikeweight.setDecimals(1)
        self.doubleSpinBox_bikeweight.setMinimum(0.100000000000000)
        self.doubleSpinBox_bikeweight.setMaximum(200.000000000000000)
        self.doubleSpinBox_bikeweight.setSingleStep(0.100000000000000)
        self.doubleSpinBox_bikeweight.setValue(80.000000000000000)
        self.label_7 = QLabel(self.settings)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(640, 80, 221, 16))
        self.spinBox_wheel_diameter = QSpinBox(self.settings)
        self.spinBox_wheel_diameter.setObjectName(u"spinBox_wheel_diameter")
        self.spinBox_wheel_diameter.setGeometry(QRect(640, 100, 231, 22))
        self.spinBox_wheel_diameter.setMinimum(1)
        self.spinBox_wheel_diameter.setMaximum(50)
        self.spinBox_wheel_diameter.setValue(27)
        self.doubleSpinBox_cwA = QDoubleSpinBox(self.settings)
        self.doubleSpinBox_cwA.setObjectName(u"doubleSpinBox_cwA")
        self.doubleSpinBox_cwA.setGeometry(QRect(640, 160, 241, 22))
        self.doubleSpinBox_cwA.setDecimals(4)
        self.doubleSpinBox_cwA.setMinimum(0.010000000000000)
        self.doubleSpinBox_cwA.setMaximum(1.000000000000000)
        self.doubleSpinBox_cwA.setSingleStep(0.100000000000000)
        self.doubleSpinBox_cwA.setValue(0.562500000000000)
        self.label_8 = QLabel(self.settings)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(640, 20, 221, 16))
        self.label_9 = QLabel(self.settings)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(640, 130, 221, 16))
        self.doubleSpinBox_rolling_resistance = QDoubleSpinBox(self.settings)
        self.doubleSpinBox_rolling_resistance.setObjectName(u"doubleSpinBox_rolling_resistance")
        self.doubleSpinBox_rolling_resistance.setGeometry(QRect(640, 220, 241, 22))
        self.doubleSpinBox_rolling_resistance.setDecimals(3)
        self.doubleSpinBox_rolling_resistance.setMinimum(0.001000000000000)
        self.doubleSpinBox_rolling_resistance.setMaximum(1.000000000000000)
        self.doubleSpinBox_rolling_resistance.setSingleStep(0.001000000000000)
        self.doubleSpinBox_rolling_resistance.setValue(0.006000000000000)
        self.label_10 = QLabel(self.settings)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(640, 190, 221, 16))
        self.label_30 = QLabel(self.settings)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(320, 210, 221, 16))
        self.comboBox_batterytype = QComboBox(self.settings)
        self.comboBox_batterytype.addItem("")
        self.comboBox_batterytype.addItem("")
        self.comboBox_batterytype.setObjectName(u"comboBox_batterytype")
        self.comboBox_batterytype.setGeometry(QRect(320, 240, 241, 22))
        self.label_31 = QLabel(self.settings)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 150, 221, 16))
        self.spinBox_rider_power = QSpinBox(self.settings)
        self.spinBox_rider_power.setObjectName(u"spinBox_rider_power")
        self.spinBox_rider_power.setGeometry(QRect(10, 170, 231, 22))
        self.spinBox_rider_power.setMinimum(1)
        self.spinBox_rider_power.setMaximum(300)
        self.spinBox_rider_power.setSingleStep(10)
        self.spinBox_rider_power.setValue(50)
        self.tabWidget.addTab(self.settings, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tab_3.setEnabled(True)
        self.tabWidget_2 = QTabWidget(self.tab_3)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 0, 1011, 741))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_18 = QLabel(self.tab)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 20, 81, 16))
        self.label_19 = QLabel(self.tab)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 60, 81, 16))
        self.label_20 = QLabel(self.tab)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 110, 81, 16))
        self.label_21 = QLabel(self.tab)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 160, 81, 16))
        self.label_22 = QLabel(self.tab)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 210, 81, 16))
        self.label_23 = QLabel(self.tab)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 260, 81, 16))
        self.label_24 = QLabel(self.tab)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(350, 20, 81, 16))
        self.label_25 = QLabel(self.tab)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(350, 60, 81, 16))
        self.label_26 = QLabel(self.tab)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(350, 110, 121, 16))
        self.label_27 = QLabel(self.tab)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(350, 160, 121, 16))
        self.label_28 = QLabel(self.tab)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(350, 210, 121, 16))
        self.label_29 = QLabel(self.tab)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(350, 260, 121, 16))
        self.label_32 = QLabel(self.tab)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(350, 310, 81, 16))
        self.label_33 = QLabel(self.tab)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 310, 111, 16))
        self.label_34 = QLabel(self.tab)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(350, 360, 121, 16))
        self.label_35 = QLabel(self.tab)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 370, 111, 16))
        self.label_36 = QLabel(self.tab)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 430, 111, 16))
        self.text_start = QLabel(self.tab)
        self.text_start.setObjectName(u"text_start")
        self.text_start.setGeometry(QRect(10, 40, 201, 16))
        self.text_end = QLabel(self.tab)
        self.text_end.setObjectName(u"text_end")
        self.text_end.setGeometry(QRect(10, 80, 201, 16))
        self.text_duration = QLabel(self.tab)
        self.text_duration.setObjectName(u"text_duration")
        self.text_duration.setGeometry(QRect(10, 130, 201, 16))
        self.text_routelength = QLabel(self.tab)
        self.text_routelength.setObjectName(u"text_routelength")
        self.text_routelength.setGeometry(QRect(10, 190, 201, 16))
        self.text_elevgain = QLabel(self.tab)
        self.text_elevgain.setObjectName(u"text_elevgain")
        self.text_elevgain.setGeometry(QRect(10, 230, 201, 16))
        self.text_elevloss = QLabel(self.tab)
        self.text_elevloss.setObjectName(u"text_elevloss")
        self.text_elevloss.setGeometry(QRect(10, 280, 201, 16))
        self.text_highestspeed = QLabel(self.tab)
        self.text_highestspeed.setObjectName(u"text_highestspeed")
        self.text_highestspeed.setGeometry(QRect(10, 340, 201, 16))
        self.text_averagespeed = QLabel(self.tab)
        self.text_averagespeed.setObjectName(u"text_averagespeed")
        self.text_averagespeed.setGeometry(QRect(10, 400, 201, 16))
        self.text_maxgradient = QLabel(self.tab)
        self.text_maxgradient.setObjectName(u"text_maxgradient")
        self.text_maxgradient.setGeometry(QRect(10, 460, 201, 16))
        self.text_socstart = QLabel(self.tab)
        self.text_socstart.setObjectName(u"text_socstart")
        self.text_socstart.setGeometry(QRect(350, 40, 201, 16))
        self.text_socend = QLabel(self.tab)
        self.text_socend.setObjectName(u"text_socend")
        self.text_socend.setGeometry(QRect(350, 80, 201, 16))
        self.text_batteryVstart = QLabel(self.tab)
        self.text_batteryVstart.setObjectName(u"text_batteryVstart")
        self.text_batteryVstart.setGeometry(QRect(350, 140, 201, 16))
        self.text_batteryVend = QLabel(self.tab)
        self.text_batteryVend.setObjectName(u"text_batteryVend")
        self.text_batteryVend.setGeometry(QRect(350, 190, 201, 16))
        self.text_batteryTempstart = QLabel(self.tab)
        self.text_batteryTempstart.setObjectName(u"text_batteryTempstart")
        self.text_batteryTempstart.setGeometry(QRect(350, 230, 201, 16))
        self.text_batteryTempend = QLabel(self.tab)
        self.text_batteryTempend.setObjectName(u"text_batteryTempend")
        self.text_batteryTempend.setGeometry(QRect(350, 280, 201, 16))
        self.text_highestpower = QLabel(self.tab)
        self.text_highestpower.setObjectName(u"text_highestpower")
        self.text_highestpower.setGeometry(QRect(350, 340, 201, 16))
        self.text_highestBatterytemp = QLabel(self.tab)
        self.text_highestBatterytemp.setObjectName(u"text_highestBatterytemp")
        self.text_highestBatterytemp.setGeometry(QRect(350, 390, 201, 16))
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.widget_browser = QWebEngineView(self.tab_4)
        self.widget_browser.setObjectName(u"widget_browser")
        self.widget_browser.setGeometry(QRect(0, 0, 1001, 711))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.graphic_plotsoc = QLabel(self.tab_2)
        self.graphic_plotsoc.setObjectName(u"graphic_plotsoc")
        self.graphic_plotsoc.setGeometry(QRect(10, 0, 991, 711))
        self.graphic_plotsoc.setScaledContents(True)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.graphic_plotpower = QLabel(self.tab_5)
        self.graphic_plotpower.setObjectName(u"graphic_plotpower")
        self.graphic_plotpower.setGeometry(QRect(0, 0, 991, 711))
        self.graphic_plotpower.setScaledContents(True)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.graphic_plotspeed = QLabel(self.tab_6)
        self.graphic_plotspeed.setObjectName(u"graphic_plotspeed")
        self.graphic_plotspeed.setGeometry(QRect(0, 0, 991, 711))
        self.graphic_plotspeed.setScaledContents(True)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.graphic_plotcurrent = QLabel(self.tab_7)
        self.graphic_plotcurrent.setObjectName(u"graphic_plotcurrent")
        self.graphic_plotcurrent.setGeometry(QRect(0, 0, 991, 711))
        self.graphic_plotcurrent.setScaledContents(True)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.graphic_plotvoltage = QLabel(self.tab_8)
        self.graphic_plotvoltage.setObjectName(u"graphic_plotvoltage")
        self.graphic_plotvoltage.setGeometry(QRect(0, 0, 991, 711))
        self.graphic_plotvoltage.setScaledContents(True)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.graphic_plotbatterytemp = QLabel(self.tab_9)
        self.graphic_plotbatterytemp.setObjectName(u"graphic_plotbatterytemp")
        self.graphic_plotbatterytemp.setGeometry(QRect(0, 0, 991, 711))
        self.graphic_plotbatterytemp.setScaledContents(True)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.label_11 = QLabel(self.tab_10)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 10, 171, 16))
        self.label_12 = QLabel(self.tab_10)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(200, 10, 61, 16))
        self.label_13 = QLabel(self.tab_10)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(260, 10, 41, 16))
        self.label_14 = QLabel(self.tab_10)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(320, 10, 41, 16))
        self.label_15 = QLabel(self.tab_10)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(380, 10, 41, 16))
        self.label_16 = QLabel(self.tab_10)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(440, 10, 41, 16))
        self.label_17 = QLabel(self.tab_10)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(500, 10, 111, 16))
        self.listWidget_time = QListWidget(self.tab_10)
        self.listWidget_time.setObjectName(u"listWidget_time")
        self.listWidget_time.setGeometry(QRect(10, 30, 171, 671))
        self.listWidget_soc = QListWidget(self.tab_10)
        self.listWidget_soc.setObjectName(u"listWidget_soc")
        self.listWidget_soc.setGeometry(QRect(190, 30, 51, 671))
        self.listWidget_power = QListWidget(self.tab_10)
        self.listWidget_power.setObjectName(u"listWidget_power")
        self.listWidget_power.setGeometry(QRect(250, 30, 51, 671))
        self.listWidget_speed = QListWidget(self.tab_10)
        self.listWidget_speed.setObjectName(u"listWidget_speed")
        self.listWidget_speed.setGeometry(QRect(310, 30, 51, 671))
        self.listWidget_current = QListWidget(self.tab_10)
        self.listWidget_current.setObjectName(u"listWidget_current")
        self.listWidget_current.setGeometry(QRect(380, 30, 51, 671))
        self.listWidget_voltage = QListWidget(self.tab_10)
        self.listWidget_voltage.setObjectName(u"listWidget_voltage")
        self.listWidget_voltage.setGeometry(QRect(440, 30, 51, 671))
        self.listWidget_batterytemp = QListWidget(self.tab_10)
        self.listWidget_batterytemp.setObjectName(u"listWidget_batterytemp")
        self.listWidget_batterytemp.setGeometry(QRect(500, 30, 51, 671))
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"EBike Simulator", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Initial SoC", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Motor efficiency", None))
        self.pushButton_loadSettings.setText(QCoreApplication.translate("MainWindow", u"Set settings", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Torque constant", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Paralell amount", None))
        self.spinBox_cell_para.setSuffix("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Battery cell capacity", None))
        self.doubleSpinBox_torque_constant.setPrefix("")
        self.doubleSpinBox_torque_constant.setSuffix(QCoreApplication.translate("MainWindow", u" Nm/A", None))
        self.doubleSpinBox_cell_capacity.setSuffix(QCoreApplication.translate("MainWindow", u" Ah", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Current loaded file", None))
        self.pushButton_loadFile.setText(QCoreApplication.translate("MainWindow", u"Load file", None))
        self.pushButton_startSimulation.setText(QCoreApplication.translate("MainWindow", u"Start simulation", None))
        self.doubleSpinBox_bikeweight.setSuffix(QCoreApplication.translate("MainWindow", u" kg", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Wheel diameter", None))
        self.spinBox_wheel_diameter.setSuffix(QCoreApplication.translate("MainWindow", u" inch", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Bike weight (bike + driver)", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"cw * A", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Rolling resistance", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Battery type", None))
        self.comboBox_batterytype.setItemText(0, QCoreApplication.translate("MainWindow", u"LiPo", None))
        self.comboBox_batterytype.setItemText(1, QCoreApplication.translate("MainWindow", u"NMC", None))

        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Rider power", None))
        self.spinBox_rider_power.setSuffix(QCoreApplication.translate("MainWindow", u" W", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), QCoreApplication.translate("MainWindow", u"Settings", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Route start", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Route end", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Duration", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Route length", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Elevation gain", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Elevation loss", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"SoC start", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"SoC end", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Battery voltage start", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Battery voltage end", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Battery temp start", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Battery temp end", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Highest power", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Highest speed", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Highest battery temp", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Average speed", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Max gradient", None))
        self.text_start.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_end.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_duration.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_routelength.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_elevgain.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_elevloss.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_highestspeed.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_averagespeed.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_maxgradient.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_socstart.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_socend.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_batteryVstart.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_batteryVend.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_batteryTempstart.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_batteryTempend.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_highestpower.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.text_highestBatterytemp.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Summary", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Map", None))
        self.graphic_plotsoc.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Plot SoC", None))
        self.graphic_plotpower.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Plot Power", None))
        self.graphic_plotspeed.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Plot Speed", None))
        self.graphic_plotcurrent.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Plot Current", None))
        self.graphic_plotvoltage.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Plot Voltage", None))
        self.graphic_plotbatterytemp.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"Plot Battery Temperature", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Time strings", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"SoC", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Power", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Speed", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Current", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Voltage", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Battery temperature", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"Raw data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Results", None))
    # retranslateUi

